#!/bin/bash

PROJECT_ROOT=$(git rev-parse --show-toplevel)
SWIFTFORMAT_CMD=${PROJECT_ROOT}/Pods/SwiftFormat/CommandLineTool/swiftformat

##### Run swiftformat and add files to index

git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
  $SWIFTFORMAT_CMD "${line}" --config "${PROJECT_ROOT}/.swiftformat"
  git add "$line"
done

echo "Swift Formatted"