#!/bin/bash

PROJECT_ROOT=$(git rev-parse --show-toplevel)
SWIFTFORMAT_CMD=${PROJECT_ROOT}/ASDKSample/Pods/SwiftFormat/CommandLineTool/swiftformat

##### Run swiftformat and add files to index

git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
  $SWIFTFORMAT_CMD "${line}" --config "${PROJECT_ROOT}/.swiftformat"
  git add "$line"
done


# Sets only once on assignment [sets path po Podfile.lock relative to git root]
podfile_lock=$(git diff --diff-filter=d --staged --name-only | grep "Podfile.lock")

# Проверка что не коммитется тестовый под в подфайле
if [ -n "$podfile_lock" ]; then
  if grep -q "TestsSharedInfrastructure" "$podfile_lock"; then
    echo "TestsSharedInfrastructure is in Podfile.lock please DO NOT commit testing pods."
    echo "Run in terminal [ make start ] command in order to rewrite Podfile.lock"
    exit 1
  fi
fi
