platform :ios, '11.0'

use_frameworks!

target 'ASDKSample' do

	pod 'TinkoffASDKCore', :path => "../"
	pod 'TinkoffASDKUI', :path => "../"

	# Linting and Formatting

	pod 'SwiftFormat/CLI', '~> 0.47.0'

end
