install! 'cocoapods', 
share_schemes_for_development_pods: true, 
preserve_pod_file_structure: true, 
generate_multiple_pod_projects: true

minimal_ios_version = '12.3'

platform :ios, minimal_ios_version

if ENV['UITEST_CONFIG'] != 'enabled'
  plugin 'cocoapods-no-autoimports'
end

use_frameworks!
target 'ASDKSample' do
  pod 'TinkoffASDKCore', :path => "../", :testspecs => ['Tests']
  pod 'TinkoffASDKUI', :path => "../", :testspecs => ['Tests']
  pod 'TinkoffASDKYandexPay', :path => '../', :testspecs => ['Tests']
  
  # Linting and Formatting
  pod 'SwiftFormat/CLI', '0.49.18' # Версия должна совпадать с версией контейнера на CI
  pod 'SwiftLint', '0.47.0' # Версия должна совпадать с версией контейнера на CI
  pod 'SwiftGen', '~> 6.0'
end

target 'ASDKSampleUITests' do
  if ENV['UITEST_CONFIG'] == 'enabled'
    pod 'UITestUtils', :git => 'https://gitlab.tcsbank.ru/coretech-mobile-ios/uitestutils.git', :tag => '1.1.3'
    pod 'TinkoffMockStrapping/Swifter', :git => 'https://github.com/tinkoff-mobile-tech/TinkoffMockStrapping.git'
    pod 'Nimble', '~> 9.2.1'
  end
end

# target 'ASDKSampleTests' do
#   pod 'TestsSharedInfrastructure', :path => '../'
# end

def install_githooks
  system("git config --local core.hooksPath \"$(git rev-parse --show-toplevel)/githooks\"")
end

post_install do |installer|
  # Устанавливаем хуки для git
  install_githooks
  # Подменяем deployment версию iOS во всех под проектах
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimal_ios_version
      end
    end
  end
end
