import_from_git(
  url: "https://github.com/tinkoff-mobile-tech/workflows.git", # The URL of the repository to import the Fastfile from.
  path: "fastlane/Fastfile" # The path of the Fastfile in the repository.
)

override_lane :extend_bump_version do |options|
  version_swift="TinkoffASDKCore/TinkoffASDKCore/Version.swift"
  relative_file_path = "../" + version_swift
  data = File.read(relative_file_path)
  data = data.gsub(/versionString = \"([\d.]+)\"/, "versionString = \"#{options[:version]}\"")
  File.write(relative_file_path, data)
  [version_swift]
end

lane :build_spm do
  scheme = "TinkoffASDK-Package"
    # xcodebuild automatically detects spm package, so you just need to pass valid scheme name
    # cocoapods project is ignored here because it is in Example folder
    spm_cache = "DerivedData/spm"
    cmd = []
    cmd << "set -o pipefail"
    cmd << "mkdir -p #{spm_cache}"
    cmd << "swift package resolve"
    cmd << "xcodebuild build -scheme #{scheme} -destination generic/platform=iOS -clonedSourcePackagesDirPath #{spm_cache} | xcpretty"
    sh(cmd.join(' && '), log: true)
end
